// Admin Mock Data
import type {
  AdminUser,
  Employee,
  Teacher,
  AdminCourse,
  CourseReview,
  CVApplication,
  JobPosting,
  AdminSupportTicket,
  Permission,
  RoleGroup,
  RevenueData,
  DashboardStats,
  AdminNotification,
  ActivityLog,
} from '../types/admin';

// Current Admin User
export const currentAdminUser: AdminUser = {
  id: 'admin-001',
  email: 'admin@edunet.com',
  firstName: 'Nguyễn',
  lastName: 'Admin',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
  role: 'super_admin',
  permissions: ['all'],
  status: 'active',
  lastLogin: '2024-12-01T08:30:00Z',
  createdAt: '2024-01-15T00:00:00Z',
};

// Dashboard Statistics
export const dashboardStats: DashboardStats = {
  totalUsers: 15420,
  totalTeachers: 234,
  totalCourses: 856,
  totalRevenue: 2850000000,
  newUsersToday: 127,
  newCoursesToday: 8,
  pendingApprovals: 23,
  openTickets: 45,
  usersGrowth: 12.5,
  revenueGrowth: 18.3,
  coursesGrowth: 8.7,
  teachersGrowth: 5.2,
};

// Revenue Data for Charts (Last 12 months)
export const revenueData: RevenueData[] = [
  { date: '2024-01', revenue: 180000000, orders: 320, refunds: 12, netRevenue: 175000000 },
  { date: '2024-02', revenue: 195000000, orders: 345, refunds: 15, netRevenue: 189000000 },
  { date: '2024-03', revenue: 220000000, orders: 410, refunds: 18, netRevenue: 212000000 },
  { date: '2024-04', revenue: 205000000, orders: 380, refunds: 14, netRevenue: 198000000 },
  { date: '2024-05', revenue: 245000000, orders: 450, refunds: 20, netRevenue: 235000000 },
  { date: '2024-06', revenue: 260000000, orders: 485, refunds: 22, netRevenue: 248000000 },
  { date: '2024-07', revenue: 235000000, orders: 420, refunds: 16, netRevenue: 228000000 },
  { date: '2024-08', revenue: 275000000, orders: 520, refunds: 25, netRevenue: 262000000 },
  { date: '2024-09', revenue: 290000000, orders: 545, refunds: 28, netRevenue: 275000000 },
  { date: '2024-10', revenue: 310000000, orders: 580, refunds: 30, netRevenue: 295000000 },
  { date: '2024-11', revenue: 285000000, orders: 530, refunds: 24, netRevenue: 272000000 },
  { date: '2024-12', revenue: 350000000, orders: 620, refunds: 32, netRevenue: 335000000 },
];

// Employees
export const employees: Employee[] = [
  {
    id: 'emp-001',
    employeeId: 'EMP001',
    firstName: 'Trần',
    lastName: 'Văn A',
    email: 'tranvana@edunet.com',
    phone: '0901234567',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    department: 'Kỹ thuật',
    position: 'Lập trình viên cao cấp',
    role: 'admin',
    status: 'active',
    hireDate: '2023-03-15',
    salary: 25000000,
    address: 'Quận 1, TP.HCM',
    createdAt: '2023-03-15T00:00:00Z',
  },
  {
    id: 'emp-002',
    employeeId: 'EMP002',
    firstName: 'Nguyễn',
    lastName: 'Thị B',
    email: 'nguyenthib@edunet.com',
    phone: '0902345678',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    department: 'Nhân sự',
    position: 'Trưởng phòng Nhân sự',
    role: 'hr',
    status: 'active',
    hireDate: '2022-06-01',
    salary: 22000000,
    address: 'Quận 3, TP.HCM',
    createdAt: '2022-06-01T00:00:00Z',
  },
  {
    id: 'emp-003',
    employeeId: 'EMP003',
    firstName: 'Lê',
    lastName: 'Văn C',
    email: 'levanc@edunet.com',
    phone: '0903456789',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    department: 'Hỗ trợ',
    position: 'Trưởng nhóm Hỗ trợ',
    role: 'support',
    status: 'active',
    hireDate: '2023-01-10',
    salary: 18000000,
    address: 'Quận 7, TP.HCM',
    createdAt: '2023-01-10T00:00:00Z',
  },
  {
    id: 'emp-004',
    employeeId: 'EMP004',
    firstName: 'Phạm',
    lastName: 'Thị D',
    email: 'phamthid@edunet.com',
    phone: '0904567890',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    department: 'Marketing',
    position: 'Chuyên viên Marketing',
    role: 'manager',
    status: 'active',
    hireDate: '2023-08-20',
    salary: 20000000,
    address: 'Quận Bình Thạnh, TP.HCM',
    createdAt: '2023-08-20T00:00:00Z',
  },
  {
    id: 'emp-005',
    employeeId: 'EMP005',
    firstName: 'Hoàng',
    lastName: 'Văn E',
    email: 'hoangvane@edunet.com',
    phone: '0905678901',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    department: 'Tài chính',
    position: 'Kế toán',
    role: 'manager',
    status: 'on_leave',
    hireDate: '2022-11-05',
    salary: 19000000,
    address: 'Quận 2, TP.HCM',
    createdAt: '2022-11-05T00:00:00Z',
  },
];

// Teachers
export const teachers: Teacher[] = [
  {
    id: 'teacher-001',
    teacherId: 'TCH001',
    firstName: 'Nguyễn',
    lastName: 'Văn Minh',
    email: 'nguyenvanminh@gmail.com',
    phone: '0911234567',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150',
    specialization: ['React', 'Node.js', 'TypeScript'],
    qualification: 'Thạc sĩ CNTT - ĐH Bách Khoa',
    experience: 8,
    rating: 4.8,
    totalCourses: 12,
    totalStudents: 3250,
    status: 'active',
    bio: 'Senior Software Engineer với 8+ năm kinh nghiệm trong lập trình web',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/nguyenvanminh',
      website: 'https://nguyenvanminh.dev',
    },
    joinedDate: '2023-02-15',
    earnings: 450000000,
  },
  {
    id: 'teacher-002',
    teacherId: 'TCH002',
    firstName: 'Trần',
    lastName: 'Thị Hương',
    email: 'tranthuhuong@gmail.com',
    phone: '0912345678',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    specialization: ['Python', 'Machine Learning', 'Data Science'],
    qualification: 'Tiến sĩ Khoa học Máy tính - ĐH Stanford',
    experience: 10,
    rating: 4.9,
    totalCourses: 8,
    totalStudents: 5420,
    status: 'active',
    bio: 'Chuyên gia AI/ML với nhiều công trình nghiên cứu được công bố quốc tế',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/tranthuhuong',
      twitter: 'https://twitter.com/tranthuhuong',
    },
    joinedDate: '2022-08-10',
    earnings: 680000000,
  },
  {
    id: 'teacher-003',
    teacherId: 'TCH003',
    firstName: 'Lê',
    lastName: 'Quang Hải',
    email: 'lequanghai@gmail.com',
    phone: '0913456789',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    specialization: ['UI/UX Design', 'Figma', 'Adobe XD'],
    qualification: 'Cử nhân Thiết kế - ĐH Mỹ Thuật',
    experience: 6,
    rating: 4.7,
    totalCourses: 6,
    totalStudents: 2180,
    status: 'active',
    bio: 'Lead Designer tại một công ty công nghệ hàng đầu Việt Nam',
    joinedDate: '2023-05-20',
    earnings: 280000000,
  },
  {
    id: 'teacher-004',
    teacherId: 'TCH004',
    firstName: 'Phạm',
    lastName: 'Đức Anh',
    email: 'phamducanh@gmail.com',
    phone: '0914567890',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    specialization: ['AWS', 'DevOps', 'Kubernetes'],
    qualification: 'Thạc sĩ CNTT - ĐH FPT',
    experience: 7,
    rating: 4.6,
    totalCourses: 5,
    totalStudents: 1890,
    status: 'pending',
    bio: 'AWS Certified Solutions Architect với kinh nghiệm triển khai hệ thống lớn',
    joinedDate: '2024-01-10',
    earnings: 0,
  },
  {
    id: 'teacher-005',
    teacherId: 'TCH005',
    firstName: 'Hoàng',
    lastName: 'Thị Mai',
    email: 'hoangthimai@gmail.com',
    phone: '0915678901',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    specialization: ['Digital Marketing', 'SEO', 'Content Marketing'],
    qualification: 'Thạc sĩ Marketing - ĐH Kinh tế',
    experience: 5,
    rating: 4.5,
    totalCourses: 4,
    totalStudents: 1560,
    status: 'active',
    bio: 'Marketing Manager với track record ấn tượng trong các chiến dịch digital',
    joinedDate: '2023-09-05',
    earnings: 195000000,
  },
];

// Admin Courses
export const adminCourses: AdminCourse[] = [
  {
    id: 'course-001',
    title: 'React Master Class - Từ Zero đến Hero',
    description: 'Khóa học React toàn diện từ cơ bản đến nâng cao, bao gồm Hooks, Redux, và TypeScript',
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400',
    category: 'Lập trình Web',
    subcategory: 'Frontend',
    teacher: { id: 'teacher-001', name: 'Nguyễn Văn Minh', avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150' },
    price: 1499000,
    discountPrice: 999000,
    duration: '45 giờ',
    totalLessons: 120,
    totalStudents: 1250,
    rating: 4.8,
    totalReviews: 456,
    status: 'published',
    level: 'intermediate',
    language: 'Tiếng Việt',
    tags: ['React', 'JavaScript', 'Frontend', 'Web Development'],
    revenue: 1248750000,
    createdAt: '2023-06-15T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
    publishedAt: '2023-07-01T00:00:00Z',
  },
  {
    id: 'course-002',
    title: 'Machine Learning với Python - Thực chiến',
    description: 'Học Machine Learning từ lý thuyết đến thực hành với các dự án thực tế',
    thumbnail: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400',
    category: 'Data Science',
    subcategory: 'Machine Learning',
    teacher: { id: 'teacher-002', name: 'Trần Thị Hương', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150' },
    price: 2499000,
    discountPrice: 1799000,
    duration: '60 giờ',
    totalLessons: 150,
    totalStudents: 2100,
    rating: 4.9,
    totalReviews: 789,
    status: 'published',
    level: 'advanced',
    language: 'Tiếng Việt',
    tags: ['Python', 'Machine Learning', 'AI', 'Data Science'],
    revenue: 3778200000,
    createdAt: '2023-03-10T00:00:00Z',
    updatedAt: '2024-11-15T00:00:00Z',
    publishedAt: '2023-04-01T00:00:00Z',
  },
  {
    id: 'course-003',
    title: 'UI/UX Design - Tạo sản phẩm thu hút người dùng',
    description: 'Khóa học thiết kế giao diện và trải nghiệm người dùng chuyên nghiệp',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400',
    category: 'Thiết kế',
    subcategory: 'UI/UX',
    teacher: { id: 'teacher-003', name: 'Lê Quang Hải', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150' },
    price: 1299000,
    discountPrice: 899000,
    duration: '35 giờ',
    totalLessons: 85,
    totalStudents: 980,
    rating: 4.7,
    totalReviews: 234,
    status: 'published',
    level: 'beginner',
    language: 'Tiếng Việt',
    tags: ['UI/UX', 'Figma', 'Design', 'Product Design'],
    revenue: 881020000,
    createdAt: '2023-08-20T00:00:00Z',
    updatedAt: '2024-10-05T00:00:00Z',
    publishedAt: '2023-09-01T00:00:00Z',
  },
  {
    id: 'course-004',
    title: 'AWS Cloud Practitioner - Chứng chỉ đầu tiên',
    description: 'Chuẩn bị cho kỳ thi AWS Cloud Practitioner với bài giảng và bài tập thực hành',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400',
    category: 'Cloud Computing',
    subcategory: 'AWS',
    teacher: { id: 'teacher-004', name: 'Phạm Đức Anh', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150' },
    price: 1199000,
    duration: '25 giờ',
    totalLessons: 60,
    totalStudents: 0,
    rating: 0,
    totalReviews: 0,
    status: 'pending',
    level: 'beginner',
    language: 'Tiếng Việt',
    tags: ['AWS', 'Cloud', 'Certification'],
    revenue: 0,
    createdAt: '2024-11-25T00:00:00Z',
    updatedAt: '2024-11-28T00:00:00Z',
  },
  {
    id: 'course-005',
    title: 'Digital Marketing A-Z',
    description: 'Tổng quan về Digital Marketing từ SEO, SEM, Social Media đến Content Marketing',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    category: 'Marketing',
    subcategory: 'Digital Marketing',
    teacher: { id: 'teacher-005', name: 'Hoàng Thị Mai', avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150' },
    price: 999000,
    discountPrice: 699000,
    duration: '30 giờ',
    totalLessons: 75,
    totalStudents: 750,
    rating: 4.5,
    totalReviews: 180,
    status: 'published',
    level: 'beginner',
    language: 'Tiếng Việt',
    tags: ['Digital Marketing', 'SEO', 'Social Media', 'Content'],
    revenue: 524250000,
    createdAt: '2023-10-10T00:00:00Z',
    updatedAt: '2024-09-15T00:00:00Z',
    publishedAt: '2023-11-01T00:00:00Z',
  },
];

// Course Reviews
export const courseReviews: CourseReview[] = [
  {
    id: 'review-001',
    courseId: 'course-001',
    courseName: 'React Master Class',
    userId: 'user-001',
    userName: 'Phạm Minh Tuấn',
    userAvatar: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=150',
    rating: 5,
    comment: 'Khóa học tuyệt vời! Giảng viên giải thích rất dễ hiểu và có nhiều ví dụ thực tế.',
    isReported: false,
    status: 'visible',
    createdAt: '2024-11-15T10:30:00Z',
  },
  {
    id: 'review-002',
    courseId: 'course-002',
    courseName: 'Machine Learning với Python',
    userId: 'user-002',
    userName: 'Nguyễn Thị Lan',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    rating: 5,
    comment: 'Nội dung chuyên sâu, phù hợp với người đã có nền tảng Python. Rất đáng giới thiệu!',
    isReported: false,
    status: 'visible',
    createdAt: '2024-11-10T14:20:00Z',
  },
  {
    id: 'review-003',
    courseId: 'course-001',
    courseName: 'React Master Class',
    userId: 'user-003',
    userName: 'Lê Hoàng Nam',
    rating: 2,
    comment: 'Khóa học này quá tệ, không đáng tiền. Nội dung copy từ nơi khác!',
    isReported: true,
    reportReason: 'Nội dung không chính xác, cố tình gây hại',
    status: 'flagged',
    createdAt: '2024-11-08T09:15:00Z',
  },
  {
    id: 'review-004',
    courseId: 'course-003',
    courseName: 'UI/UX Design',
    userId: 'user-004',
    userName: 'Trần Văn Đức',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    rating: 4,
    comment: 'Khóa học tốt, nhưng có thể thêm nhiều bài tập thực hành hơn.',
    isReported: false,
    status: 'visible',
    createdAt: '2024-11-05T16:45:00Z',
  },
];

// CV Applications
export const cvApplications: CVApplication[] = [
  {
    id: 'cv-001',
    applicantName: 'Nguyễn Văn Hùng',
    email: 'nguyenvanhung@gmail.com',
    phone: '0921234567',
    position: 'Lập trình viên Frontend cao cấp',
    department: 'Kỹ thuật',
    cvUrl: '/uploads/cv/nguyen-van-hung.pdf',
    coverLetter: 'Tôi rất quan tâm đến vị trí này và tin rằng kinh nghiệm 5 năm của tôi sẽ phù hợp...',
    experience: 5,
    education: 'Cử nhân CNTT - ĐH Bách Khoa HCM',
    skills: ['React', 'TypeScript', 'Node.js', 'AWS'],
    expectedSalary: 30000000,
    availability: 'Ngay lập tức',
    status: 'shortlisted',
    rating: 4,
    notes: 'Ứng viên có profile tốt, cần phỏng vấn kỹ thuật',
    interviewDate: '2024-12-05T09:00:00Z',
    appliedAt: '2024-11-20T08:30:00Z',
    source: 'linkedin',
  },
  {
    id: 'cv-002',
    applicantName: 'Trần Thị Hoa',
    email: 'tranthihoa@gmail.com',
    phone: '0922345678',
    position: 'Nhà thiết kế UI/UX',
    department: 'Thiết kế',
    cvUrl: '/uploads/cv/tran-thi-hoa.pdf',
    experience: 3,
    education: 'Cử nhân Thiết kế Đồ họa - ĐH Mỹ Thuật',
    skills: ['Figma', 'Adobe XD', 'Sketch', 'Illustrator'],
    expectedSalary: 20000000,
    availability: '2 tuần',
    status: 'reviewing',
    appliedAt: '2024-11-22T10:15:00Z',
    source: 'website',
  },
  {
    id: 'cv-003',
    applicantName: 'Lê Minh Đức',
    email: 'leminhduc@gmail.com',
    phone: '0923456789',
    position: 'Chuyên viên Content Marketing',
    department: 'Marketing',
    cvUrl: '/uploads/cv/le-minh-duc.pdf',
    coverLetter: 'Với đam mê về content và kinh nghiệm làm việc với các startup...',
    experience: 2,
    education: 'Cử nhân Báo chí - ĐH KHXH&NV',
    skills: ['Content Writing', 'SEO', 'Social Media', 'Canva'],
    expectedSalary: 15000000,
    availability: '1 tháng',
    status: 'new',
    appliedAt: '2024-11-28T14:00:00Z',
    source: 'referral',
  },
  {
    id: 'cv-004',
    applicantName: 'Phạm Quốc Bảo',
    email: 'phamquocbao@gmail.com',
    phone: '0924567890',
    position: 'Kỹ sư DevOps',
    department: 'Kỹ thuật',
    cvUrl: '/uploads/cv/pham-quoc-bao.pdf',
    experience: 4,
    education: 'Thạc sĩ CNTT - ĐH FPT',
    skills: ['Docker', 'Kubernetes', 'AWS', 'CI/CD', 'Terraform'],
    expectedSalary: 35000000,
    availability: 'Ngay lập tức',
    status: 'interview',
    rating: 5,
    notes: 'Ứng viên xuất sắc, có chứng chỉ AWS',
    interviewDate: '2024-12-03T14:00:00Z',
    appliedAt: '2024-11-15T09:45:00Z',
    source: 'linkedin',
  },
];

// Job Postings
export const jobPostings: JobPosting[] = [
  {
    id: 'job-001',
    title: 'Lập trình viên Frontend cao cấp',
    department: 'Kỹ thuật',
    location: 'TP. Hồ Chí Minh',
    type: 'full-time',
    description: 'Chúng tôi đang tìm kiếm Lập trình viên Frontend cao cấp để tham gia phát triển nền tảng EdTech hàng đầu Việt Nam.',
    requirements: [
      '5+ năm kinh nghiệm với React/Vue',
      'Thành thạo TypeScript',
      'Hiểu biết về UI/UX',
      'Kinh nghiệm với REST API và GraphQL',
    ],
    benefits: [
      'Lương cạnh tranh: 25-35 triệu',
      'Thưởng KPI hàng quý',
      'Bảo hiểm sức khỏe cao cấp',
      '15 ngày phép/năm',
    ],
    salaryRange: { min: 25000000, max: 35000000 },
    status: 'active',
    applicationsCount: 12,
    deadline: '2024-12-31',
    createdAt: '2024-11-01T00:00:00Z',
  },
  {
    id: 'job-002',
    title: 'Nhà thiết kế UI/UX',
    department: 'Thiết kế',
    location: 'TP. Hồ Chí Minh',
    type: 'full-time',
    description: 'Tìm kiếm Nhà thiết kế UI/UX sáng tạo để thiết kế giao diện cho các sản phẩm giáo dục.',
    requirements: [
      '3+ năm kinh nghiệm thiết kế UI/UX',
      'Thành thạo Figma, Adobe XD',
      'Có portfolio ấn tượng',
      'Hiểu biết về Design System',
    ],
    benefits: [
      'Lương: 18-25 triệu',
      'Môi trường sáng tạo',
      'Được đào tạo liên tục',
      'Team building hàng tháng',
    ],
    salaryRange: { min: 18000000, max: 25000000 },
    status: 'active',
    applicationsCount: 8,
    deadline: '2024-12-25',
    createdAt: '2024-11-05T00:00:00Z',
  },
  {
    id: 'job-003',
    title: 'Thực tập sinh Marketing',
    department: 'Marketing',
    location: 'TP. Hồ Chí Minh',
    type: 'internship',
    description: 'Cơ hội thực tập tại bộ phận Marketing của EduNet, học hỏi từ các chuyên gia.',
    requirements: [
      'Sinh viên năm cuối ngành Marketing/Truyền thông',
      'Năng động, sáng tạo',
      'Kỹ năng viết tốt',
      'Có thể làm việc full-time',
    ],
    benefits: [
      'Phụ cấp: 5-7 triệu',
      'Cơ hội trở thành nhân viên chính thức',
      'Được mentor 1-1',
      'Chứng nhận thực tập',
    ],
    salaryRange: { min: 5000000, max: 7000000 },
    status: 'active',
    applicationsCount: 25,
    deadline: '2024-12-15',
    createdAt: '2024-11-10T00:00:00Z',
  },
];

// Support Tickets
export const supportTickets: AdminSupportTicket[] = [
  {
    id: 'ticket-001',
    ticketId: 'TKT-2024-001',
    userId: 'user-001',
    userName: 'Nguyễn Minh Tú',
    userEmail: 'nguyenminhtu@gmail.com',
    userAvatar: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=150',
    subject: 'Không thể truy cập khóa học đã mua',
    description: 'Tôi đã mua khóa học React Master Class nhưng không thể xem được video. Hệ thống báo lỗi "Access Denied".',
    category: 'technical',
    priority: 'high',
    status: 'in_progress',
    assignedTo: 'emp-003',
    assignedName: 'Lê Văn C',
    responses: [
      {
        id: 'resp-001',
        message: 'Chào bạn, cảm ơn bạn đã liên hệ. Chúng tôi đang kiểm tra vấn đề này.',
        authorId: 'emp-003',
        authorName: 'Lê Văn C',
        isStaff: true,
        createdAt: '2024-11-29T10:30:00Z',
      },
    ],
    createdAt: '2024-11-29T09:15:00Z',
    updatedAt: '2024-11-29T10:30:00Z',
  },
  {
    id: 'ticket-002',
    ticketId: 'TKT-2024-002',
    userId: 'user-002',
    userName: 'Trần Thị Lan',
    userEmail: 'tranthilan@gmail.com',
    subject: 'Yêu cầu hoàn tiền',
    description: 'Tôi muốn hoàn tiền khóa học UI/UX Design vì nội dung không phù hợp với mô tả.',
    category: 'billing',
    priority: 'medium',
    status: 'open',
    responses: [],
    createdAt: '2024-11-30T14:20:00Z',
    updatedAt: '2024-11-30T14:20:00Z',
  },
  {
    id: 'ticket-003',
    ticketId: 'TKT-2024-003',
    userId: 'user-003',
    userName: 'Lê Hoàng Nam',
    userEmail: 'lehoangnam@gmail.com',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    subject: 'Không nhận được chứng chỉ',
    description: 'Tôi đã hoàn thành khóa học Python cách đây 1 tuần nhưng chưa nhận được chứng chỉ.',
    category: 'course',
    priority: 'low',
    status: 'resolved',
    assignedTo: 'emp-003',
    assignedName: 'Lê Văn C',
    responses: [
      {
        id: 'resp-002',
        message: 'Chào bạn, chứng chỉ đã được gửi về email của bạn. Vui lòng kiểm tra thư mục spam.',
        authorId: 'emp-003',
        authorName: 'Lê Văn C',
        isStaff: true,
        createdAt: '2024-11-28T11:00:00Z',
      },
      {
        id: 'resp-003',
        message: 'Tôi đã nhận được rồi. Cảm ơn bạn!',
        authorId: 'user-003',
        authorName: 'Lê Hoàng Nam',
        isStaff: false,
        createdAt: '2024-11-28T11:30:00Z',
      },
    ],
    createdAt: '2024-11-28T08:45:00Z',
    updatedAt: '2024-11-28T11:30:00Z',
    resolvedAt: '2024-11-28T11:30:00Z',
  },
];

// Permissions
export const permissions: Permission[] = [
  // Dashboard
  { id: 'perm-001', name: 'Xem Bảng điều khiển', code: 'dashboard.view', description: 'Xem tổng quan bảng điều khiển', module: 'Bảng điều khiển' },
  // Users
  { id: 'perm-002', name: 'Xem danh sách người dùng', code: 'users.view', description: 'Xem danh sách tất cả người dùng', module: 'Người dùng' },
  { id: 'perm-003', name: 'Chỉnh sửa người dùng', code: 'users.edit', description: 'Chỉnh sửa thông tin người dùng', module: 'Người dùng' },
  { id: 'perm-004', name: 'Xóa người dùng', code: 'users.delete', description: 'Xóa người dùng khỏi hệ thống', module: 'Người dùng' },
  // Courses
  { id: 'perm-005', name: 'Xem khóa học', code: 'courses.view', description: 'Xem danh sách khóa học', module: 'Khóa học' },
  { id: 'perm-006', name: 'Duyệt khóa học', code: 'courses.approve', description: 'Duyệt khóa học mới', module: 'Khóa học' },
  { id: 'perm-007', name: 'Khóa khóa học', code: 'courses.lock', description: 'Khóa/mở khóa khóa học', module: 'Khóa học' },
  { id: 'perm-008', name: 'Xóa khóa học', code: 'courses.delete', description: 'Xóa khóa học', module: 'Khóa học' },
  // Teachers
  { id: 'perm-009', name: 'Xem giáo viên', code: 'teachers.view', description: 'Xem danh sách giáo viên', module: 'Giáo viên' },
  { id: 'perm-010', name: 'Duyệt giáo viên', code: 'teachers.approve', description: 'Duyệt giáo viên mới', module: 'Giáo viên' },
  { id: 'perm-011', name: 'Quản lý giáo viên', code: 'teachers.manage', description: 'Quản lý thông tin giáo viên', module: 'Giáo viên' },
  // Employees
  { id: 'perm-012', name: 'Xem nhân viên', code: 'employees.view', description: 'Xem danh sách nhân viên', module: 'Nhân viên' },
  { id: 'perm-013', name: 'Quản lý nhân viên', code: 'employees.manage', description: 'Thêm/sửa/xóa nhân viên', module: 'Nhân viên' },
  // Support
  { id: 'perm-014', name: 'Xem ticket', code: 'support.view', description: 'Xem danh sách ticket hỗ trợ', module: 'Hỗ trợ' },
  { id: 'perm-015', name: 'Xử lý ticket', code: 'support.handle', description: 'Xử lý và phản hồi ticket', module: 'Hỗ trợ' },
  // Revenue
  { id: 'perm-016', name: 'Xem doanh thu', code: 'revenue.view', description: 'Xem báo cáo doanh thu', module: 'Doanh thu' },
  { id: 'perm-017', name: 'Xuất báo cáo', code: 'revenue.export', description: 'Xuất báo cáo doanh thu', module: 'Doanh thu' },
  // Settings
  { id: 'perm-018', name: 'Quản lý cài đặt', code: 'settings.manage', description: 'Quản lý cài đặt hệ thống', module: 'Cài đặt' },
  { id: 'perm-019', name: 'Quản lý quyền', code: 'permissions.manage', description: 'Quản lý quyền và nhóm quyền', module: 'Phân quyền' },
  // Recruitment
  { id: 'perm-020', name: 'Xem tuyển dụng', code: 'recruitment.view', description: 'Xem danh sách CV và tin tuyển dụng', module: 'Tuyển dụng' },
  { id: 'perm-021', name: 'Quản lý tuyển dụng', code: 'recruitment.manage', description: 'Quản lý quy trình tuyển dụng', module: 'Tuyển dụng' },
];

// Role Groups
export const roleGroups: RoleGroup[] = [
  {
    id: 'role-001',
    name: 'Quản trị viên cao cấp',
    description: 'Toàn quyền quản trị hệ thống',
    permissions: permissions.map(p => p.code),
    usersCount: 1,
    isSystem: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'role-002',
    name: 'Quản trị viên',
    description: 'Quản trị viên với hầu hết các quyền',
    permissions: [
      'dashboard.view', 'users.view', 'users.edit', 'courses.view', 'courses.approve',
      'courses.lock', 'teachers.view', 'teachers.approve', 'teachers.manage',
      'support.view', 'support.handle', 'revenue.view',
    ],
    usersCount: 2,
    isSystem: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'role-003',
    name: 'Trưởng phòng Nhân sự',
    description: 'Quản lý nhân sự và tuyển dụng',
    permissions: [
      'dashboard.view', 'employees.view', 'employees.manage',
      'recruitment.view', 'recruitment.manage',
    ],
    usersCount: 1,
    isSystem: false,
    createdAt: '2024-02-15T00:00:00Z',
  },
  {
    id: 'role-004',
    name: 'Nhân viên Hỗ trợ',
    description: 'Nhân viên hỗ trợ khách hàng',
    permissions: [
      'dashboard.view', 'users.view', 'support.view', 'support.handle',
    ],
    usersCount: 3,
    isSystem: false,
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'role-005',
    name: 'Quản lý Khóa học',
    description: 'Quản lý khóa học và giáo viên',
    permissions: [
      'dashboard.view', 'courses.view', 'courses.approve', 'courses.lock',
      'teachers.view', 'teachers.approve', 'teachers.manage',
    ],
    usersCount: 2,
    isSystem: false,
    createdAt: '2024-04-10T00:00:00Z',
  },
];

// Admin Notifications
export const adminNotifications: AdminNotification[] = [
  {
    id: 'notif-001',
    title: 'Khóa học mới chờ duyệt',
    message: 'Có 3 khóa học mới đang chờ được phê duyệt',
    type: 'info',
    category: 'course',
    isRead: false,
    link: '/admin/courses?status=pending',
    createdAt: '2024-12-01T08:00:00Z',
  },
  {
    id: 'notif-002',
    title: 'Doanh thu tháng 11 tăng',
    message: 'Doanh thu tháng 11 tăng 18% so với tháng trước',
    type: 'success',
    category: 'revenue',
    isRead: false,
    link: '/admin/revenue',
    createdAt: '2024-12-01T07:30:00Z',
  },
  {
    id: 'notif-003',
    title: 'Ticket khẩn cấp',
    message: 'Có 2 ticket ưu tiên cao cần xử lý ngay',
    type: 'warning',
    category: 'support',
    isRead: true,
    link: '/admin/support?priority=high',
    createdAt: '2024-11-30T16:45:00Z',
  },
  {
    id: 'notif-004',
    title: 'Review bị báo cáo',
    message: '1 review đã bị báo cáo và cần kiểm tra',
    type: 'error',
    category: 'course',
    isRead: false,
    link: '/admin/courses/reviews?status=flagged',
    createdAt: '2024-11-30T14:20:00Z',
  },
];

// Activity Logs
export const activityLogs: ActivityLog[] = [
  {
    id: 'log-001',
    userId: 'admin-001',
    userName: 'Nguyễn Admin',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    action: 'Đăng nhập',
    details: 'Đăng nhập thành công vào hệ thống admin',
    ipAddress: '192.168.1.100',
    module: 'Auth',
    createdAt: '2024-12-01T08:30:00Z',
  },
  {
    id: 'log-002',
    userId: 'emp-002',
    userName: 'Nguyễn Thị B',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    action: 'Tạo nhân viên mới',
    details: 'Thêm nhân viên mới: Hoàng Văn F - Marketing',
    module: 'Employees',
    createdAt: '2024-11-30T15:20:00Z',
  },
  {
    id: 'log-003',
    userId: 'admin-001',
    userName: 'Nguyễn Admin',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    action: 'Duyệt khóa học',
    details: 'Duyệt khóa học: Node.js Advanced - Trần Văn X',
    module: 'Courses',
    createdAt: '2024-11-30T11:45:00Z',
  },
  {
    id: 'log-004',
    userId: 'emp-003',
    userName: 'Lê Văn C',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    action: 'Đóng ticket',
    details: 'Đóng ticket TKT-2024-003: Không nhận được chứng chỉ',
    module: 'Support',
    createdAt: '2024-11-28T11:35:00Z',
  },
];

// Categories for filters
export const courseCategories = [
  'Lập trình Web',
  'Data Science',
  'Thiết kế',
  'Cloud Computing',
  'Marketing',
  'Mobile Development',
  'DevOps',
  'Kinh doanh',
];

export const departments = [
  'Kỹ thuật',
  'Nhân sự',
  'Hỗ trợ',
  'Marketing',
  'Tài chính',
  'Thiết kế',
  'Vận hành',
];

export const ticketCategories = [
  { value: 'technical', label: 'Kỹ thuật' },
  { value: 'billing', label: 'Thanh toán' },
  { value: 'course', label: 'Khóa học' },
  { value: 'account', label: 'Tài khoản' },
  { value: 'other', label: 'Khác' },
];

export const ticketPriorities = [
  { value: 'low', label: 'Thấp', color: 'default' },
  { value: 'medium', label: 'Trung bình', color: 'blue' },
  { value: 'high', label: 'Cao', color: 'orange' },
  { value: 'urgent', label: 'Khẩn cấp', color: 'red' },
];

export const ticketStatuses = [
  { value: 'open', label: 'Mở', color: 'blue' },
  { value: 'in_progress', label: 'Đang xử lý', color: 'orange' },
  { value: 'waiting', label: 'Chờ phản hồi', color: 'purple' },
  { value: 'resolved', label: 'Đã giải quyết', color: 'green' },
  { value: 'closed', label: 'Đã đóng', color: 'default' },
];

export const courseStatuses = [
  { value: 'draft', label: 'Bản nháp', color: 'default' },
  { value: 'pending', label: 'Chờ duyệt', color: 'orange' },
  { value: 'approved', label: 'Đã duyệt', color: 'blue' },
  { value: 'rejected', label: 'Từ chối', color: 'red' },
  { value: 'published', label: 'Đã xuất bản', color: 'green' },
  { value: 'archived', label: 'Lưu trữ', color: 'default' },
];

export const teacherStatuses = [
  { value: 'active', label: 'Hoạt động', color: 'green' },
  { value: 'inactive', label: 'Không hoạt động', color: 'default' },
  { value: 'pending', label: 'Chờ duyệt', color: 'orange' },
  { value: 'suspended', label: 'Tạm ngưng', color: 'red' },
];

export const employeeStatuses = [
  { value: 'active', label: 'Đang làm việc', color: 'green' },
  { value: 'inactive', label: 'Nghỉ việc', color: 'default' },
  { value: 'on_leave', label: 'Nghỉ phép', color: 'orange' },
];

export const employeeRoles = [
  { value: 'super_admin', label: 'Quản trị viên cao cấp', color: 'red' },
  { value: 'admin', label: 'Quản trị viên', color: 'blue' },
  { value: 'manager', label: 'Quản lý', color: 'purple' },
  { value: 'hr', label: 'Nhân sự', color: 'cyan' },
  { value: 'support', label: 'Hỗ trợ', color: 'green' },
  { value: 'staff', label: 'Nhân viên', color: 'default' },
];

export const cvStatuses = [
  { value: 'new', label: 'Mới', color: 'blue' },
  { value: 'reviewing', label: 'Đang xem xét', color: 'orange' },
  { value: 'shortlisted', label: 'Vào vòng trong', color: 'purple' },
  { value: 'interview', label: 'Phỏng vấn', color: 'cyan' },
  { value: 'offered', label: 'Đã offer', color: 'green' },
  { value: 'hired', label: 'Đã tuyển', color: 'green' },
  { value: 'rejected', label: 'Từ chối', color: 'red' },
];

// Alias for Support page
export const supportCategories = ticketCategories;

// Application statuses alias
export const applicationStatuses = cvStatuses;

// Job posting statuses
export const jobStatuses = [
  { value: 'draft', label: 'Bản nháp', color: 'default' },
  { value: 'active', label: 'Đang tuyển', color: 'green' },
  { value: 'paused', label: 'Tạm dừng', color: 'orange' },
  { value: 'closed', label: 'Đã đóng', color: 'default' },
];
