import type { 
  ClassMember, 
  LearningPath, 
  AssignmentItem, 
  QuizItem, 
  MaterialItem, 
  NotificationItem 
} from '../types/myCourse';

// Mock class members data
export const MOCK_CLASS_MEMBERS: ClassMember[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@email.com',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    role: 'teacher',
    joinedAt: '2024-01-15',
    status: 'active',
  },
  {
    id: '2',
    name: 'Emily Johnson',
    email: 'emily.johnson@email.com',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    role: 'student',
    joinedAt: '2024-02-01',
    status: 'active',
    progress: 75,
  },
  {
    id: '3',
    name: 'Michael Brown',
    email: 'michael.brown@email.com',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    role: 'student',
    joinedAt: '2024-02-05',
    status: 'active',
    progress: 60,
  },
  {
    id: '4',
    name: 'Sarah Davis',
    email: 'sarah.davis@email.com',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    role: 'student',
    joinedAt: '2024-02-10',
    status: 'active',
    progress: 90,
  },
  {
    id: '5',
    name: 'David Wilson',
    email: 'david.wilson@email.com',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    role: 'assistant',
    joinedAt: '2024-01-20',
    status: 'active',
  },
  {
    id: '6',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@email.com',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    role: 'student',
    joinedAt: '2024-02-15',
    status: 'inactive',
    progress: 30,
  },
];

// Mock learning path data
export const MOCK_LEARNING_PATH: LearningPath[] = [
  {
    id: '1',
    title: 'Giới thiệu Phát triển Web',
    description: 'Học cơ bản về HTML, CSS và JavaScript',
    order: 1,
    duration: '2 giờ',
    status: 'completed',
    lessons: [
      { id: '1-1', title: 'Phát triển Web là gì?', type: 'video', duration: '15 phút', completed: true },
      { id: '1-2', title: 'Thiết lập Môi trường', type: 'reading', duration: '10 phút', completed: true },
      { id: '1-3', title: 'Trang HTML Đầu tiên', type: 'video', duration: '20 phút', completed: true },
      { id: '1-4', title: 'Kiểm tra Mô-đun', type: 'quiz', duration: '15 phút', completed: true },
    ],
  },
  {
    id: '2',
    title: 'Nền tảng CSS',
    description: 'Thành thạo nghệ thuật định dạng trang web',
    order: 2,
    duration: '3 giờ',
    status: 'in-progress',
    lessons: [
      { id: '2-1', title: 'Bộ chọn CSS', type: 'video', duration: '25 phút', completed: true },
      { id: '2-2', title: 'Mô hình hộp', type: 'video', duration: '20 phút', completed: true },
      { id: '2-3', title: 'Bố cục Flexbox', type: 'video', duration: '30 phút', completed: false },
      { id: '2-4', title: 'CSS Grid', type: 'video', duration: '30 phút', completed: false },
      { id: '2-5', title: 'Bài tập thực hành', type: 'assignment', duration: '45 phút', completed: false },
    ],
  },
  {
    id: '3',
    title: 'JavaScript Cơ bản',
    description: 'Thêm tương tác cho website của bạn',
    order: 3,
    duration: '4 giờ',
    status: 'available',
    lessons: [
      { id: '3-1', title: 'Biến và Kiểu dữ liệu', type: 'video', duration: '25 phút', completed: false },
      { id: '3-2', title: 'Hàm và Phạm vi', type: 'video', duration: '30 phút', completed: false },
      { id: '3-3', title: 'Thao tác DOM', type: 'video', duration: '35 phút', completed: false },
      { id: '3-4', title: 'Sự kiện và Xử lý', type: 'video', duration: '30 phút', completed: false },
      { id: '3-5', title: 'Dự án cuối kỳ', type: 'assignment', duration: '60 phút', completed: false },
    ],
  },
  {
    id: '4',
    title: 'Nền tảng React',
    description: 'Xây dựng giao diện người dùng hiện đại với React',
    order: 4,
    duration: '5 giờ',
    status: 'locked',
    lessons: [
      { id: '4-1', title: 'Giới thiệu React', type: 'video', duration: '20 phút', completed: false },
      { id: '4-2', title: 'Component và Props', type: 'video', duration: '30 phút', completed: false },
      { id: '4-3', title: 'State và Vòng đời', type: 'video', duration: '35 phút', completed: false },
      { id: '4-4', title: 'Tìm hiểu sâu về Hooks', type: 'video', duration: '40 phút', completed: false },
    ],
  },
];

// Mock assignments data
export const MOCK_ASSIGNMENTS: AssignmentItem[] = [
  {
    id: '1',
    title: 'Xây dựng Portfolio Cá nhân',
    description: 'Tạo website portfolio cá nhân responsive sử dụng HTML và CSS',
    dueDate: '2024-12-15',
    status: 'pending',
    maxGrade: 100,
    attachments: ['portfolio-requirements.pdf'],
  },
  {
    id: '2',
    title: 'Máy tính JavaScript',
    description: 'Xây dựng máy tính hoạt động sử dụng JavaScript thuần',
    dueDate: '2024-12-10',
    status: 'submitted',
    submittedAt: '2024-12-08',
    maxGrade: 100,
    attachments: ['calculator-specs.pdf'],
  },
  {
    id: '3',
    title: 'Bố cục CSS Flexbox',
    description: 'Tái tạo thiết kế cho trước sử dụng CSS Flexbox',
    dueDate: '2024-12-01',
    status: 'graded',
    grade: 95,
    maxGrade: 100,
    attachments: ['flexbox-design.png'],
    feedback: 'Làm rất tốt! Chú ý chi tiết xuất sắc.',
  },
  {
    id: '4',
    title: 'Thanh điều hướng Responsive',
    description: 'Tạo menu điều hướng responsive cho di động',
    dueDate: '2024-11-25',
    status: 'overdue',
    maxGrade: 100,
    attachments: ['nav-requirements.pdf'],
  },
];

// Mock quizzes data
export const MOCK_QUIZZES: QuizItem[] = [
  {
    id: '1',
    title: 'Kiểm tra Nền tảng HTML',
    description: 'Kiểm tra kiến thức cơ bản về HTML',
    duration: 15,
    questions: 20,
    attempts: 2,
    maxAttempts: 3,
    bestScore: 85,
    status: 'completed',
  },
  {
    id: '2',
    title: 'Kiểm tra Bộ chọn CSS',
    description: 'Thành thạo kiến thức về bộ chọn CSS',
    duration: 20,
    questions: 25,
    attempts: 1,
    maxAttempts: 3,
    bestScore: 72,
    status: 'completed',
  },
  {
    id: '3',
    title: 'Kiểm tra JavaScript Cơ bản',
    description: 'Kiểm tra nền tảng JavaScript của bạn',
    duration: 30,
    questions: 30,
    attempts: 0,
    maxAttempts: 3,
    status: 'not-started',
    dueDate: '2024-12-20',
  },
  {
    id: '4',
    title: 'Kiểm tra Component React',
    description: 'Hiểu về các mẫu component trong React',
    duration: 25,
    questions: 20,
    attempts: 0,
    maxAttempts: 2,
    status: 'not-started',
    dueDate: '2024-12-25',
  },
];

// Mock materials data
export const MOCK_MATERIALS: MaterialItem[] = [
  {
    id: '1',
    title: 'Đề cương Khóa học',
    type: 'pdf',
    size: '2.5 MB',
    uploadedAt: '2024-01-15',
    downloadUrl: '/materials/syllabus.pdf',
    description: 'Đề cương và mục tiêu khóa học đầy đủ',
  },
  {
    id: '2',
    title: 'Bảng tóm tắt HTML',
    type: 'pdf',
    size: '1.2 MB',
    uploadedAt: '2024-02-01',
    downloadUrl: '/materials/html-cheat-sheet.pdf',
    description: 'Tài liệu tham khảo nhanh các thẻ HTML',
  },
  {
    id: '3',
    title: 'Tham khảo Thuộc tính CSS',
    type: 'document',
    size: '3.8 MB',
    uploadedAt: '2024-02-10',
    downloadUrl: '/materials/css-reference.docx',
    description: 'Tài liệu thuộc tính CSS toàn diện',
  },
  {
    id: '4',
    title: 'Hướng dẫn JavaScript ES6',
    type: 'video',
    size: '150 MB',
    uploadedAt: '2024-02-15',
    downloadUrl: '/materials/es6-tutorial.mp4',
    description: 'Video hướng dẫn về các tính năng ES6',
  },
  {
    id: '5',
    title: 'Tài liệu React',
    type: 'link',
    uploadedAt: '2024-02-20',
    downloadUrl: 'https://reactjs.org/docs',
    description: 'Tài liệu React chính thức',
  },
  {
    id: '6',
    title: 'Tài nguyên Dự án',
    type: 'image',
    size: '25 MB',
    uploadedAt: '2024-02-25',
    downloadUrl: '/materials/project-assets.zip',
    description: 'Hình ảnh và biểu tượng cho các dự án',
  },
];

// Mock notifications data
export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: '1',
    title: 'Bài tập mới được đăng',
    content: 'Bài tập mới "Xây dựng Portfolio Cá nhân" đã được đăng. Hạn nộp: 15 tháng 12, 2024.',
    type: 'assignment',
    createdAt: '2024-12-01T10:00:00',
    isRead: false,
    author: {
      name: 'John Smith',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
  },
  {
    id: '2',
    title: 'Đã chấm điểm',
    content: 'Điểm của bạn cho bài tập "Bố cục CSS Flexbox" đã được công bố. Bạn đạt 95/100.',
    type: 'grade',
    createdAt: '2024-11-28T14:30:00',
    isRead: true,
    author: {
      name: 'John Smith',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
  },
  {
    id: '3',
    title: 'Thay đổi lịch học',
    content: 'Lớp học dự kiến ngày 5 tháng 12 đã được chuyển sang ngày 6 tháng 12 lúc 3:00 PM.',
    type: 'announcement',
    createdAt: '2024-11-25T09:00:00',
    isRead: true,
    author: {
      name: 'John Smith',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
  },
  {
    id: '4',
    title: 'Nhắc nhở Kiểm tra',
    content: 'Đừng quên! Bài kiểm tra JavaScript Cơ bản hạn nộp ngày 20 tháng 12, 2024.',
    type: 'reminder',
    createdAt: '2024-11-20T08:00:00',
    isRead: false,
    author: {
      name: 'Hệ thống',
      avatar: '',
    },
  },
  {
    id: '5',
    title: 'Chào mừng đến khóa học!',
    content: 'Chào mừng bạn đến với Nền tảng Phát triển Web! Chúng tôi rất vui được có bạn tại đây.',
    type: 'general',
    createdAt: '2024-01-15T09:00:00',
    isRead: true,
    author: {
      name: 'John Smith',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
  },
];

// Mock courses list
export const MOCK_MY_COURSES = [
  {
    key: '1',
    id: 1,
    image: 'https://img.freepik.com/free-photo/programming-background-with-person-working-with-codes-computer_23-2150010125.jpg',
    title: 'Khóa học Phát triển Web Toàn diện 2.0',
    teacher: 'Nguyễn Văn Minh',
    status: 'learning',
    lessons: '12/25',
    progress: 48,
    category: 'Phát triển Web',
    nextLesson: 'Bố cục Flexbox',
    nextLessonTime: 'Ngày mai lúc 10:00 SA',
  },
  {
    key: '2',
    id: 2,
    image: 'https://img.freepik.com/free-photo/digital-marketing-with-icons-business-people_53876-94833.jpg',
    title: 'Tiếp thị Số Nâng cao',
    teacher: 'Hoàng Thị Mai',
    status: 'completed',
    lessons: '18/18',
    progress: 100,
    category: 'Tiếp thị',
    completedDate: '2024-11-15',
  },
  {
    key: '3',
    id: 3,
    image: 'https://img.freepik.com/free-photo/graphic-designer-working-tablet_23-2147652935.jpg',
    title: 'Thiết kế Đồ họa Nâng cao',
    teacher: 'Lê Quang Hải',
    status: 'pending',
    lessons: '0/30',
    progress: 0,
    category: 'Thiết kế',
    startDate: '2024-12-15',
  },
  {
    key: '4',
    id: 4,
    image: 'https://img.freepik.com/free-photo/ai-technology-microchip-background-digital-transformation-concept_53876-124669.jpg',
    title: 'Nền tảng Học Máy',
    teacher: 'Trần Thị Hương',
    status: 'learning',
    lessons: '8/20',
    progress: 40,
    category: 'AI & ML',
    nextLesson: 'Mạng Thần kinh',
    nextLessonTime: '5 Tháng 12 lúc 2:00 CH',
  },
];
