import type { ScheduleEvent } from '../types/schedule';

export const MOCK_SCHEDULE_EVENTS: ScheduleEvent[] = [
  {
    id: '1',
    title: 'Lớp Phát triển Web',
    courseId: '1',
    courseName: 'Khóa học Phát triển Web Toàn diện',
    type: 'class',
    date: '2024-12-08',
    startTime: '08:00',
    endTime: '10:00',
    description: 'Nền tảng HTML & CSS - Xây dựng bố cục',
    instructor: 'Nguyễn Văn Minh',
    location: 'Trực tuyến - Zoom',
    status: 'upcoming',
    color: '#3B82F6',
  },
  {
    id: '2',
    title: 'Buổi học React Cơ bản',
    courseId: '1',
    courseName: 'Khóa học Phát triển Web Toàn diện',
    type: 'class',
    date: '2024-12-10',
    startTime: '10:00',
    endTime: '12:00',
    description: 'Giới thiệu về component và props trong React',
    instructor: 'Nguyễn Văn Minh',
    location: 'Trực tuyến - Zoom',
    status: 'upcoming',
    color: '#3B82F6',
  },
  {
    id: '3',
    title: 'Hạn nộp bài Portfolio',
    courseId: '1',
    courseName: 'Khóa học Phát triển Web Toàn diện',
    type: 'deadline',
    date: '2024-12-15',
    startTime: '23:59',
    endTime: '23:59',
    description: 'Nộp dự án portfolio cá nhân',
    status: 'upcoming',
    color: '#EF4444',
  },
  {
    id: '4',
    title: 'Workshop Thiết kế UI/UX',
    courseId: '3',
    courseName: 'Lớp Thiết kế Đồ họa Nâng cao',
    type: 'class',
    date: '2024-12-09',
    startTime: '14:00',
    endTime: '16:00',
    description: 'Cơ bản Figma và nguyên tắc thiết kế',
    instructor: 'Lê Quang Hải',
    location: 'Trực tuyến - Google Meet',
    status: 'upcoming',
    color: '#8B5CF6',
  },
  {
    id: '5',
    title: 'Kiểm tra JavaScript',
    courseId: '1',
    courseName: 'Khóa học Phát triển Web Toàn diện',
    type: 'quiz',
    date: '2024-12-20',
    startTime: '09:00',
    endTime: '10:00',
    description: 'Kiểm tra kiến thức nền tảng JavaScript',
    status: 'upcoming',
    color: '#10B981',
  },
  {
    id: '6',
    title: 'Giới thiệu Học Máy',
    courseId: '4',
    courseName: 'Nền tảng Học Máy',
    type: 'class',
    date: '2024-12-05',
    startTime: '14:00',
    endTime: '16:00',
    description: 'Giới thiệu về Mạng thần kinh',
    instructor: 'Trần Thị Hương',
    location: 'Trực tuyến - Zoom',
    status: 'upcoming',
    color: '#F59E0B',
  },
  {
    id: '7',
    title: 'Hướng dẫn 1-1',
    courseId: '1',
    courseName: 'Khóa học Phát triển Web Toàn diện',
    type: 'meeting',
    date: '2024-12-12',
    startTime: '15:00',
    endTime: '15:30',
    description: 'Đánh giá tiến độ và giải đáp thắc mắc',
    instructor: 'Nguyễn Văn Minh',
    location: 'Trực tuyến - Zoom',
    status: 'upcoming',
    color: '#EC4899',
  },
  {
    id: '8',
    title: 'Bài tập CSS Flexbox',
    courseId: '1',
    courseName: 'Khóa học Phát triển Web Toàn diện',
    type: 'assignment',
    date: '2024-12-18',
    startTime: '23:59',
    endTime: '23:59',
    description: 'Tạo bố cục responsive sử dụng Flexbox',
    status: 'upcoming',
    color: '#F97316',
  },
];

export const EVENT_TYPE_CONFIG = {
  class: { label: 'Lớp học', color: '#3B82F6', bgColor: 'bg-blue-50', textColor: 'text-blue-600', borderColor: 'border-blue-200' },
  assignment: { label: 'Bài tập', color: '#F97316', bgColor: 'bg-orange-50', textColor: 'text-orange-600', borderColor: 'border-orange-200' },
  quiz: { label: 'Kiểm tra', color: '#10B981', bgColor: 'bg-green-50', textColor: 'text-green-600', borderColor: 'border-green-200' },
  meeting: { label: 'Cuộc họp', color: '#EC4899', bgColor: 'bg-pink-50', textColor: 'text-pink-600', borderColor: 'border-pink-200' },
  deadline: { label: 'Hạn chót', color: '#EF4444', bgColor: 'bg-red-50', textColor: 'text-red-600', borderColor: 'border-red-200' },
};
